### ISSUE TITLE
fuzz results

### ISSUE THREAD

**Issue by sgraham** [nico/demumble#2]
I'm guessing you don't care at all as these are upstream somewhere, but just in case, here's some files that make demumble assert (via afl-fuzz-2.41b). 
They all seem to hit this:
    demumble: third_party/wine/undname.c:217: str_array_push: Assertion `ptr' failed.

[crashes.tar.gz](https://github.com/nico/demumble/files/1042964/crashes.tar.gz)

**Comment by nico** [comment]
"Fixed" by replacing the wine undname implementation with the new llvm MicrosoftDemangler in c9a1e03649f57 (…which currently isn't fuzzed either, https://llvm.org/PR39582 , so it's likely crashy too, but The Process should get to that eventually.)
