### ISSUE TITLE
demumble '.?AVlength_error@std@@' crashes

### ISSUE THREAD

**Issue by tanderson-google** [nico/demumble#7]
The following crashes:
$ demumble '?AVlength_error@std@@'
[1]    211865 segmentation fault  

But this doesn't:
$ demumble '.?AVlength_error@std@@'     
.?AVlength_error@std@@

Possibly a bug in upstream LLVM.

**Comment by nico** [comment]
Thanks for the report!

As it happens, I've been fixing lots and lots of crash-on-invalid bugs upstram about a month ago, and this is already fixed on master as of 633d0e5cab. I'll make a new release at some point – let me know if you feel this warrants doing this earlier rather than later.

**Comment by nico** [comment]
The new 1.2.1 release should fix this and many more similar issues: https://github.com/nico/demumble/releases

**Comment by stevemk14ebr** [comment]
This is an RTTI prefix. Probably crashed because it's similar style to normal mangled name, but the prefix differs enough. https://github.com/nico/demumble/issues/9
