### ISSUE TITLE
Failed to demangle complex function name created from heavily templated lambda function

### ISSUE THREAD

**Issue by tobig** [nico/demumble#8]
Hi Nico,

I just tried your demangle tool and it works really great. Unfortunately, it seems it cannot demangle this crazy complex name. As you seem to also work on LLVM's lib/Demangle maybe you are also interested in such failed demangle reports.

```_ZNSt3__116__variant_detail12__visitation6__base12__dispatcherIJLm3EEE10__dispatchIONS1_9__variant15__value_visitorIZNK6libint20TransprecisionMatrixINS8_8TypeListIJsilEEENS_16integer_sequenceImJLm8ELm16ELm32EEEEE11readElementEmmEUlTyRT_E_EEJRKNS0_6__baseILNS0_6_TraitE1EJNS8_6MatrixILm8EsEENSM_ILm8EiEENSM_ILm8ElEENSM_ILm16EsEENSM_ILm16EiEENSM_ILm16ElEENSM_ILm32EsEENSM_ILm32EiEENSM_ILm32ElEEEEEEEEDcSF_DpT0_```

**Comment by nico** [comment]
Thanks for the report! Do you happen to have the source code and compiler invocation that produced this? (godbolt would be ideal.)

Failing that: Is this from cl.exe or clang-cl? Can you paste the symbol in a code block so that github doesn't interpret the embedded `_`s as markup for italics?

(And demumble just uses lib/Demangle nowadays, so technically this should probably go to bugs.llvm.org – but it doesn't really matter. I can definitely look into it.)

**Comment by tobig** [comment]
Hi Nico,

it seems lib/Demangle breaks even for simple lambdas. c++filt, as used by godbolt, can handle these, but will break on more complicated files, I assume. Here a small reproducer:

https://godbolt.org/z/PaToaC

(It fails even without the integer parameter, but I wanted a test case where also the non-lambda function requires mangling)

**Comment by nico** [comment]
This seems to work for me; maybe you didn't quote the `$_0` when testing locally?

```
$ demumble '_ZZ3fooiENK3$_0clEi'
foo(int)::$_0::operator()(int) const
```

**Comment by tobig** [comment]
```
$~/Downloads/demumble '_ZZ3fooiENK3$_0clEi'
foo(int)::$_0::operator()(int) const
$c++filt '_ZZ3fooiENK3$_0clEi'
foo(int)::$_0::operator()(int) const
$echo '_ZZ3fooiENK3$_0clEi' | c++filt 
foo(int)::$_0::operator()(int) const
$echo '_ZZ3fooiENK3$_0clEi' | ~/Downloads/demumble 
_ZZ3fooiENK3$_0clEi
```

**Comment by nico** [comment]
Thanks, I fixed the problem in https://github.com/nico/demumble/issues/8#issuecomment-526810673 in f1a071ed8ee03403eb7eafbfc785473850a54479. Is there more to do here for the earlier comments?

**Comment by nico** [comment]
The Itanium spec says "Mangled names containing '$' or '.' are reserved for private implementation use. Names produced using such extensions are inherently non-portable and should be given internal linkage where possible."

demumble currently doesn't accept '.' as Itanium mangle char. I guess I'll wait with adding that until there's a need, since '.' is also a common punctuation char.

**Comment by tobig** [comment]
> Thanks, I fixed the problem in [#8 (comment)](https://github.com/nico/demumble/issues/8#issuecomment-526810673) in [f1a071e](https://github.com/nico/demumble/commit/f1a071ed8ee03403eb7eafbfc785473850a54479).

I can confirm that this fix addresses the lambda via stdin issue:

```
$echo '_ZZ3fooiENK3$_0clEi' | ./demumble
foo(int)::$_0::operator()(int) const
```

**Comment by tobig** [comment]
Here is a reproducer for the original test case:

https://godbolt.org/z/AjbJwm

The .cpp file is large as it includes a lot of std includes after preprocessing. The relevant function name after mangling is: 

```@"_ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm32ElEEEEDaSM_"```

which demumble does not demangle even when passed as argument

```
$~/Projects/demumble/demumble _ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm32ElEEEEDaSM_
_ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3
```
I spent around two hours reducing the test case. I hope that the main offending functions are now at the very end of the file. Let me know if this is sufficient or if I should try to reduce further.

**Comment by nico** [comment]
I don't see that symbol, but I see three symbols similar to the one you mention in that godbolt link:

`_ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm8EsEEEEDaSM_`, `_ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm8EiEEEEDaSM_`, `_ZZN6libint11visitMatrixINS_8TypeListIJsilEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm8ElEEEEDaSM_`

They also don't demumble, so I'll look at those. Thanks for the repro!

**Comment by nico** [comment]
This version compiles on my mac: https://godbolt.org/z/C9w4zi

**Comment by nico** [comment]
Looks like the mangling changed recently-ish. Xcode clang produces `_ZZN6libint11visitMatrixINS_8TypeListIJsixEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlRSE_E_clINS_6MatrixILm8EsEEEEDaSM_` which demumbles fine:

```
$ demumble '_ZZN6libint11visitMatrixINS_8TypeListIJsixEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlRSE_E_clINS_6MatrixILm8EsEEEEDaSM_'
auto void libint::visitMatrix<libint::TypeList<short, int, long long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul>, void, 1, isl_map_coalesce_libint(libint::TransprecisionMatrix<libint::TypeList<short, int, long long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul> >&)::$_0&>(isl_map_coalesce_libint(libint::TransprecisionMatrix<libint::TypeList<short, int, long long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul> >&)::$_0&, libint::TransprecisionMatrix<libint::TypeList<short, int, long long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul> >::MatrixVariant&)::'lambda'(libint::TypeList<short, int, long long>&)::operator()<libint::Matrix<8ul, short> >(libint::TypeList<short, int, long long>&) const
```

Trunk clang produces `_ZZN6libint11visitMatrixINS_8TypeListIJsixEEENSt3__116integer_sequenceImJLm8ELm16ELm32EEEEvLi1ERZ23isl_map_coalesce_libintRNS_20TransprecisionMatrixIS2_S5_EEE3$_0JEEET1_OT3_RNS6_IT_T0_E13MatrixVariantEDpRT4_ENKUlTyRSE_E_clINS_6MatrixILm8EsEEEEDaSM_` which doesn't demumble.

**Comment by nico** [comment]
After peeling away many layers of template goo, this remains:

```
template <typename F> void visit(F &&f, int v) { return f(v); }

template <typename F> void visitMatrix(F &&f, int matrix) {
  visit([&f](auto &mat) { return f(mat); }, matrix);
}

void myfun() {
  visitMatrix([](auto& mat) {}, 15);
}
```

Xcode clang produces `_ZZ11visitMatrixIZ5myfunvE3$_0EvOT_iENKUlRS1_E_clIiEEDaS3_` for the lambda in the 2nd function, which demumbles to `auto void visitMatrix<myfun()::$_0>(myfun()::$_0&&, int)::'lambda'(myfun()::$_0&)::operator()<int>(myfun()::$_0&) const`. Trunk clang instead produces `_ZZ11visitMatrixIZ5myfunvE3$_0EvOT_iENKUlTyRS1_E_clIiEEDaS3_`.

**Comment by tobig** [comment]
Wow, this is impressive

**Comment by tobig** [comment]
commit 8205a814a691bfa62fed911b58b0a306ab5efe31
Author: Hamza Sood <hamza_sood@me.com>
Date:   Sat May 4 10:49:46 2019 +0000

    [c++20] Implement P0428R2 - Familiar template syntax for generic lambdas
    
    Differential Revision: https://reviews.llvm.org/D36527

might be relevant

**Comment by nico** [comment]
Yup, just finished filing http://llvm.org/PR43213 :)

**Comment by tobig** [comment]
Thx.

**Comment by nico** [comment]
Update: If you use clang r370991+ to build your program, it might now produces symbols that demumble can handle.

If you do indeed use lambdas with explicit template arguments, then that's still TBD.

**Comment by tobig** [comment]
Yes, I cross-checked and can confirm that this very issue has been resolved. 

I spotted a minor difference between c++filt and demumble:

```
$cat c++filt 
std::__1::optional<unsigned long> simplex::Simplex<simplex::Options<libint::TransprecisionMatrix<libint::TypeList<short>, std::__1::integer_sequence<unsigned long, 16ul> >, true, true, true, false> >::findPivotRow(std::__1::optional<unsigned long>, std::__1::optional<simplex::Simplex<simplex::Options<libint::TransprecisionMatrix<libint::TypeList<short>, std::__1::integer_sequence<unsigned long, 16ul> >, true, true, true, false> >::Direction>, int) const::{lambda(auto:1&)#1}::operator()<libint::Matrix<16ul, short> const>(libint::Matrix<16ul, short> const&) const
$cat demum 
std::__1::optional<unsigned long> simplex::Simplex<simplex::Options<libint::TransprecisionMatrix<libint::TypeList<short>, std::__1::integer_sequence<unsigned long, 16ul> >, true, true, true, false> >::findPivotRow(std::__1::optional<unsigned long>, std::__1::optional<simplex::Simplex<simplex::Options<libint::TransprecisionMatrix<libint::TypeList<short>, std::__1::integer_sequence<unsigned long, 16ul> >, true, true, true, false> >::Direction>, int) const::'lambda'(auto&)::operator()<libint::Matrix<16ul, short> const>(auto&) const
```
for the symbol: 
```
_ZZNK7simplex7SimplexINS_7OptionsIN6libint20TransprecisionMatrixINS2_8TypeListIJsEEENSt3__116integer_sequenceImJLm16EEEEEELb1ELb1ELb1ELb0EEEE12findPivotRowENS6_8optionalImEENSC_INSB_9DirectionEEEiENKUlRT_E_clIKNS2_6MatrixILm16EsEEEESD_SH_ 
```
it seems demumble uses auto as the type of the lambda argument whereas c++filt uses the instantiated type. For me both work, but maybe this difference is of interest to you.

**Comment by tobig** [comment]
Also, I don't use explicit template arguments.

**Comment by nico** [comment]
https://github.com/nico/demumble/commit/6b6cb515dace99947c58ddaa97ceffe3ca8600c4 adds support for demangling explicit template arguments, so this is now completely done, and demumble can demangle the (incorrectly mangled) symbol in the original report:

```
$ ./demumble '_ZNSt3__116__variant_detail12__visitation6__base12__dispatcherIJLm3EEE10__dispatchIONS1_9__variant15__value_visitorIZNK6libint20TransprecisionMatrixINS8_8TypeListIJsilEEENS_16integer_sequenceImJLm8ELm16ELm32EEEEE11readElementEmmEUlTyRT_E_EEJRKNS0_6__baseILNS0_6_TraitE1EJNS8_6MatrixILm8EsEENSM_ILm8EiEENSM_ILm8ElEENSM_ILm16EsEENSM_ILm16EiEENSM_ILm16ElEENSM_ILm32EsEENSM_ILm32EiEENSM_ILm32ElEEEEEEEEDcSF_DpT0_'
decltype(auto) std::__1::__variant_detail::__visitation::__base::__dispatcher<3ul>::__dispatch<std::__1::__variant_detail::__visitation::__variant::__value_visitor<libint::TransprecisionMatrix<libint::TypeList<short, int, long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul> >::readElement(unsigned long, unsigned long) const::'lambda'<typename $T>(libint::TypeList<short, int, long>&)>&&, std::__1::__variant_detail::__base<(std::__1::__variant_detail::_Trait)1, libint::Matrix<8ul, short>, libint::Matrix<8ul, int>, libint::Matrix<8ul, long>, libint::Matrix<16ul, short>, libint::Matrix<16ul, int>, libint::Matrix<16ul, long>, libint::Matrix<32ul, short>, libint::Matrix<32ul, int>, libint::Matrix<32ul, long> > const&>(libint::TypeList<short, int, long>, std::__1::integer_sequence<unsigned long, 8ul, 16ul, 32ul>...)
```

Thanks for pointing out that difference – since both print the template instantiation args, printing `auto` seems shorter and doesn't lose information, so I think I like demumble's behavior :)

**Comment by tobig** [comment]
Perfect. Thanks a lot!
